"""
generate_scenario.py
====================
Programmatically generates/validates the SUMO scenario files.
Can regenerate routes with custom demand parameters.

Usage:
    python simulation/generate_scenario.py --demand medium --seed 42 --duration 3600
"""

import argparse
import os
import sys
import xml.etree.ElementTree as ET
from pathlib import Path
from typing import Dict

# ---------------------------------------------------------------------------
# Demand presets
# ---------------------------------------------------------------------------
DEMAND_PRESETS: Dict[str, Dict[str, int]] = {
    "low": {
        "NS_peak": 200,
        "SN_peak": 180,
        "EW_peak": 190,
        "WE_peak": 170,
    },
    "medium": {
        "NS_peak": 400,
        "SN_peak": 360,
        "EW_peak": 380,
        "WE_peak": 340,
    },
    "high": {
        "NS_peak": 650,
        "SN_peak": 600,
        "EW_peak": 620,
        "WE_peak": 570,
    },
    "asymmetric_ns": {
        "NS_peak": 700,
        "SN_peak": 650,
        "EW_peak": 180,
        "WE_peak": 160,
    },
    "asymmetric_ew": {
        "NS_peak": 180,
        "SN_peak": 160,
        "EW_peak": 680,
        "WE_peak": 630,
    },
}

SUMO_DIR = Path(__file__).parent / "sumo"
DATA_DIR = Path(__file__).parent.parent / "data" / "raw"


def generate_routes(demand: str, seed: int, duration: int) -> str:
    """
    Generate a SUMO routes XML string for the given demand level.
    """
    d = DEMAND_PRESETS.get(demand, DEMAND_PRESETS["medium"])
    ns = d["NS_peak"]
    sn = d["SN_peak"]
    ew = d["EW_peak"]
    we = d["WE_peak"]

    turns_vph = max(40, ns // 8)  # proportional turning traffic

    xml = f"""<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by generate_scenario.py | demand={demand} | seed={seed} | duration={duration}s -->
<routes xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:noNamespaceSchemaLocation="http://sumo.dlr.de/xsd/routes_file.xsd">

    <vType id="car"   accel="2.6" decel="4.5" sigma="0.5" length="5"  minGap="2.5" maxSpeed="13.89" guiShape="passenger"/>
    <vType id="truck" accel="1.0" decel="3.0" sigma="0.5" length="12" minGap="3.0" maxSpeed="9.72"  guiShape="truck"/>

    <!-- Straight through -->
    <route id="r_NS" edges="N2C C2S"/>
    <route id="r_SN" edges="S2C C2N"/>
    <route id="r_EW" edges="E2C C2W"/>
    <route id="r_WE" edges="W2C C2E"/>

    <!-- Turning movements -->
    <route id="r_NE" edges="N2C C2E"/>
    <route id="r_NW" edges="N2C C2W"/>
    <route id="r_SE" edges="S2C C2E"/>
    <route id="r_SW" edges="S2C C2W"/>
    <route id="r_EN" edges="E2C C2N"/>
    <route id="r_ES" edges="E2C C2S"/>
    <route id="r_WN" edges="W2C C2N"/>
    <route id="r_WS" edges="W2C C2S"/>

    <!-- Warmup: light traffic (0 - 300 s) -->
    <flow id="fw_NS" route="r_NS" begin="0"   end="300" vehsPerHour="{ns//4}"  type="car" departLane="best" departSpeed="max" randomTrips="1"/>
    <flow id="fw_SN" route="r_SN" begin="0"   end="300" vehsPerHour="{sn//4}"  type="car" departLane="best" departSpeed="max" randomTrips="1"/>
    <flow id="fw_EW" route="r_EW" begin="0"   end="300" vehsPerHour="{ew//4}"  type="car" departLane="best" departSpeed="max" randomTrips="1"/>
    <flow id="fw_WE" route="r_WE" begin="0"   end="300" vehsPerHour="{we//4}"  type="car" departLane="best" departSpeed="max" randomTrips="1"/>

    <!-- Main demand (300 - {duration} s) -->
    <flow id="fm_NS" route="r_NS" begin="300" end="{duration}" vehsPerHour="{ns}"  type="car" departLane="best" departSpeed="max" randomTrips="1"/>
    <flow id="fm_SN" route="r_SN" begin="300" end="{duration}" vehsPerHour="{sn}"  type="car" departLane="best" departSpeed="max" randomTrips="1"/>
    <flow id="fm_EW" route="r_EW" begin="300" end="{duration}" vehsPerHour="{ew}"  type="car" departLane="best" departSpeed="max" randomTrips="1"/>
    <flow id="fm_WE" route="r_WE" begin="300" end="{duration}" vehsPerHour="{we}"  type="car" departLane="best" departSpeed="max" randomTrips="1"/>

    <!-- Turns -->
    <flow id="ft_NE" route="r_NE" begin="0" end="{duration}" vehsPerHour="{turns_vph}" type="car" departLane="best" departSpeed="max" randomTrips="1"/>
    <flow id="ft_NW" route="r_NW" begin="0" end="{duration}" vehsPerHour="{turns_vph}" type="car" departLane="best" departSpeed="max" randomTrips="1"/>
    <flow id="ft_SE" route="r_SE" begin="0" end="{duration}" vehsPerHour="{turns_vph}" type="car" departLane="best" departSpeed="max" randomTrips="1"/>
    <flow id="ft_SW" route="r_SW" begin="0" end="{duration}" vehsPerHour="{turns_vph}" type="car" departLane="best" departSpeed="max" randomTrips="1"/>
    <flow id="ft_EN" route="r_EN" begin="0" end="{duration}" vehsPerHour="{turns_vph}" type="car" departLane="best" departSpeed="max" randomTrips="1"/>
    <flow id="ft_ES" route="r_ES" begin="0" end="{duration}" vehsPerHour="{turns_vph}" type="car" departLane="best" departSpeed="max" randomTrips="1"/>
    <flow id="ft_WN" route="r_WN" begin="0" end="{duration}" vehsPerHour="{turns_vph}" type="car" departLane="best" departSpeed="max" randomTrips="1"/>
    <flow id="ft_WS" route="r_WS" begin="0" end="{duration}" vehsPerHour="{turns_vph}" type="car" departLane="best" departSpeed="max" randomTrips="1"/>

    <!-- Trucks -->
    <flow id="ftrk_NS" route="r_NS" begin="300" end="{duration}" vehsPerHour="20" type="truck" departLane="best" departSpeed="0" randomTrips="1"/>
    <flow id="ftrk_EW" route="r_EW" begin="300" end="{duration}" vehsPerHour="15" type="truck" departLane="best" departSpeed="0" randomTrips="1"/>

</routes>
"""
    return xml


def generate_sumocfg(duration: int, seed: int) -> str:
    """Generate the .sumocfg with updated duration and seed."""
    return f"""<?xml version="1.0" encoding="UTF-8"?>
<configuration xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
               xsi:noNamespaceSchemaLocation="http://sumo.dlr.de/xsd/sumoConfiguration.xsd">
    <input>
        <net-file value="network.net.xml"/>
        <route-files value="routes.rou.xml"/>
        <additional-files value="additional.add.xml"/>
    </input>
    <output>
        <tripinfo-output value="../../data/raw/tripinfo.xml"/>
        <summary-output value="../../data/raw/summary.xml"/>
        <queue-output value="../../data/raw/queue.xml"/>
    </output>
    <time>
        <begin value="0"/>
        <end value="{duration}"/>
        <step-length value="1"/>
    </time>
    <processing>
        <collision.action value="warn"/>
        <time-to-teleport value="300"/>
        <ignore-route-errors value="true"/>
    </processing>
    <random_number>
        <seed value="{seed}"/>
    </random_number>
    <report>
        <verbose value="false"/>
        <no-step-log value="true"/>
        <no-warnings value="false"/>
    </report>
</configuration>
"""


def check_sumo_installed() -> bool:
    """Check whether SUMO is available on PATH."""
    import shutil
    sumo_bin = shutil.which("sumo") or shutil.which("sumo.exe")
    return sumo_bin is not None


def main():
    parser = argparse.ArgumentParser(
        description="Generate/Regenerate SUMO scenario files for the Agentic AI Traffic prototype."
    )
    parser.add_argument("--demand", default="medium",
                        choices=list(DEMAND_PRESETS.keys()),
                        help="Traffic demand preset")
    parser.add_argument("--seed", type=int, default=42,
                        help="Random seed for reproducibility")
    parser.add_argument("--duration", type=int, default=3600,
                        help="Simulation duration in seconds")
    args = parser.parse_args()

    print(f"[generate_scenario] demand={args.demand} | seed={args.seed} | duration={args.duration}s")

    # Ensure output directories exist
    SUMO_DIR.mkdir(parents=True, exist_ok=True)
    DATA_DIR.mkdir(parents=True, exist_ok=True)
    (DATA_DIR.parent.parent / "data" / "results").mkdir(parents=True, exist_ok=True)

    # Write routes file
    routes_path = SUMO_DIR / "routes.rou.xml"
    routes_xml = generate_routes(args.demand, args.seed, args.duration)
    routes_path.write_text(routes_xml, encoding="utf-8")
    print(f"  Written: {routes_path}")

    # Write sumocfg
    cfg_path = SUMO_DIR / "simulation.sumocfg"
    cfg_xml = generate_sumocfg(args.duration, args.seed)
    cfg_path.write_text(cfg_xml, encoding="utf-8")
    print(f"  Written: {cfg_path}")

    # SUMO check
    if check_sumo_installed():
        print("[SUMO] SUMO is installed and on PATH. Ready to run.")
    else:
        print(
            "\n[WARNING] SUMO is NOT detected on PATH.\n"
            "  Install SUMO from: https://sumo.dlr.de/docs/Downloads.php\n"
            "  After installing, add SUMO_HOME to your environment variables.\n"
            "  Example (PowerShell):\n"
            "    $env:SUMO_HOME = 'C:\\Program Files (x86)\\Eclipse\\Sumo'\n"
            "    $env:PATH += ';' + $env:SUMO_HOME + '\\bin'\n"
            "  The prototype will still partially run without SUMO (backend + frontend).\n"
            "  The simulation will use mock data when SUMO is unavailable.\n"
        )

    print("\n[generate_scenario] Done. Files are ready.")


if __name__ == "__main__":
    main()
